---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitter
  template:
    metadata:
      labels:
        app: twitter
    spec:
      containers:
        - name: app
          image: ghcr.io/demimurg/twitter
          ports:
            - containerPort: 80
        - name: ui
          image: fullstorydev/grpcui
          ports:
            - containerPort: 8080
          # should bind to all ips (0.0.0.0) to be able to expose port
          command: ["grpcui", "-bind=0.0.0.0", "-port=8080", "-plaintext", "localhost:80"]
---
apiVersion: v1
kind: Service
metadata:
  name: twitter
spec:
  type: NodePort
  selector:
    app: twitter
  ports:
    - port: 8080
      nodePort: 30000