---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitter
  template:
    metadata:
      labels:
        app: twitter
    spec:
      containers:
        - name: app
          image: ghcr.io/demimurg/twitter
          ports:
            - containerPort: 80 # app server
            - containerPort: 81 # grpc ui
            - containerPort: 82 # prometheus
        - name: db
          image: postgres:alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
---
apiVersion: v1
kind: Service
metadata:
  name: twitter
spec:
  type: NodePort
  selector:
    app: twitter
  ports:
    - port: 81
      nodePort: 30000