apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    hash: {{ randAlphaNum 6 }} # to redeploy resource each time
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}:latest
          readinessProbe:
            tcpSocket:
              port: 80
          ports:
            - containerPort: 80 # app server
            - containerPort: 81 # grpc ui
            - containerPort: 82 # prometheus
          env:
          {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end}}
