apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: twitter-ingress
spec:
  rules:
    - host: twitter.{{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: twitter
                port:
                  number: 81
    - host: grafana.{{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 80