apiVersion: apps/v1
kind: Deployment
metadata:
    name: mimir
    labels:
        app: mimir
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mimir
    template:
        metadata:
            labels:
                app: mimir
        spec:
            containers:
                - name: mimir
                  image: {{ .Values.mimir.image }}
                  args:
                      - -config.file=/etc/mimir/config.yaml
                  ports:
                      - containerPort: 9009
                  volumeMounts:
                      - name: config-volume
                        mountPath: /etc/mimir
            volumes:
                - name: config-volume
                  configMap:
                      name: mimir

---

apiVersion: v1
kind: ConfigMap
metadata:
    name: mimir
data:
    config.yaml: |
        multitenancy_enabled: false

        blocks_storage:
            backend: filesystem
            bucket_store:
                sync_dir: /tmp/mimir/tsdb-sync
            filesystem:
                dir: /tmp/mimir/data/tsdb
            tsdb:
                dir: /tmp/mimir/tsdb

        compactor:
            data_dir: /tmp/mimir/compactor
            sharding_ring:
                kvstore:
                    store: memberlist

        distributor:
            ring:
                instance_addr: 127.0.0.1
                kvstore:
                    store: memberlist

        ingester:
            ring:
                instance_addr: 127.0.0.1
                kvstore:
                    store: memberlist
                replication_factor: 1

        ruler_storage:
            backend: filesystem
            filesystem:
                dir: /tmp/mimir/rules

        server:
            http_listen_port: 9009
            log_level: info

        store_gateway:
            sharding_ring:
                replication_factor: 1

---

apiVersion: v1
kind: Service
metadata:
    name: mimir
spec:
    selector:
        app: mimir
    ports:
        - port: 9009