apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: grpc
      port: 80
    - name: prom
      port: 82
    - name: grpcui
      port: 81

---

apiVersion: v1
kind: Service
metadata:
  name: postgresql-ext
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: twitter
    app.kubernetes.io/name: postgresql
  ports:
    - port: 5432
      nodePort: 30001
