image: ghcr.io/demimurg/twitter
replicas: 1
host: "<secret>"

env:
  LOG_LEVEL: info
  MIGRATIONS_DIR: "./migrations"
  POSTGRESQL_DSN: "<secret>"

  # --------------------------------------- INFRA ---------------------------------------

postgresql:
  fullnameOverride: postgresql
  auth:
    postgresPassword: "<secret>"
  primary:
    persistence:
      size: 10Gi

grafana:
  fullnameOverride: grafana
  persistence:
    enabled: true
    size: 2Gi