name: Basic
on: [push]

jobs:
  go-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    container: golang:1.19-alpine
    steps:
      - uses: actions/checkout@v3
      - name: vendor
        run: go mod vendor
      - name: go test
        run: CGO_ENABLED=0 go test -coverpkg=./... ./...
      
