name: Basic
on: [push]

jobs:
  go-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    container: golang:1.19-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: CGO_ENABLED=0 go test -coverpkg=./... ./...
  golangci-lint:
    name: Run Linter
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:v1.50-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Start check with golangci-lint
        run: golangci-lint run
  docker-image:
    name: Build and Push Docker
    needs: [go-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log into the container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up docker buildx engine
        uses: docker/setup-buildx-action@v2
      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}:latest
  deploy-kube:
    name: Deploy Image to Kubernetes
    needs: [docker-image]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-hub/kubectl@v1.26.0
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: replace --force -f k8s.yaml
            
