name: Basic
on: [push]

jobs:
  go-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    container: golang:1.19-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Go Test
        run: CGO_ENABLED=0 go test -coverpkg=./... ./...
  golangci-lint:
    name: Run linter
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:v1.50-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Golangci Lint
        run: golangci-lint run
  docker-image:
    name: Build and push docker image
    needs: [go-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }},latest
          labels: ${{ steps.meta.outputs.labels }}
