name: Basic
on: [push]

jobs:
  go-test:
    name: Run unit tests for ${{ GITHUB_REPOSITORY }}
    runs-on: ubuntu-latest
    container: golang:1.19-alpine
    steps:
      - uses: actions/checkout@v3
      - run: go mod vendor
      - run: go test ./...
      
