name: Basic
on: [push]

jobs:
  go-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    container: golang:1.19-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Go Test
        run: CGO_ENABLED=0 go test -coverpkg=./... ./...
  golangci-lint:
    name: Run Linter
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:v1.50-alpine
    steps:
      - uses: actions/checkout@v3
      - name: start check with golangci-lint
        run: golangci-lint run
  docker-image:
    name: Build and Push Docker Image
    needs: [go-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: log into the container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: set up docker buildx engine
        uses: docker/setup-buildx-action@v2
      - name: build and push dockerimage
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}:latest
  deploy-kube:
    name: Deploy Image to Kubernetes Cluster
    needs: [docker-image]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup kubectl client
        run: snap install kubectl --classic && echo ${{ secrets.KUBECONFIG }} | base64 --decode > .kube/config
      - name: deploy kubernetes resources
        run: kubectl replace --force -f k8s.yaml
            
